#pragma once

enum LAYER_CONSTANTS {
	LAYER_WORLD_BACKGROUND,
	LAYER_WORLD_MIDGROUND,
	LAYER_WORLD_PARTICLE,
	LAYER_WORLD_FOREGROUND,
	LAYER_WORLD_POSTPROCESS,
	LAYER_FIRST_UI,
	LAYER_SECOND_UI,
	LAYER_MAX
};
